---
- name: teste
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: teste
      shell:
        mkdir /etc/teste
    - name: teste
      command:
        cat /etc/hosts
    - name: teste
      apt: 
        name: nmap
      
...
